Repository curtistarr/bee-sharps, pull requests merged in 2019-10, with the labels that each got.

#1 plot test and full csv in main.py
  server/dataset.csv
  server/main.py
Labels: back-end

#2 Move api to seperate module
  .idea/bee-sharps.iml
  Pipfile
  Pipfile.lock
  server/README.md
  server/api/__init__.py
  server/api/api.py
  server/api/test_app.py
  server/main.py
  server/plotting/__init__.py
  server/plotting/plotter.py
Labels: back-end

#3 race graph
  server/race.py
Labels: back-end

#5 Moving graph creation to plotter
  server/plotting/plotter.py
  server/race.py
Labels: back-end

#6 Visualise sex against interview status
  server/plotting/plotter.py
Labels: back-end, testing completed

#8 Making generic plot x vs interviewed method
  server/plotting/plotter.py
Labels: back-end

#9 Adding simple component
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/SimpleComponent.js
  webapp/src/components/SimpleComponent.test.js
Labels: front-end
